config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars, only: [:index, :new, :create, :show, :destroy] do
    resources :bookings, only: [:create]
  end
  resources :reviews, only: [:destroy, :show]
  resources :bookings, only: [:index, :destroy, :show] do
    resources :reviews, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  has_one :review, dependent: :destroy
  validates :start_date, :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :brand, :model, :mileage, :year, :body_type, :location, :price, :transmission, presence: true
  validates :mileage, :numericality => { :greater_than_or_equal_to => 0 }
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch
  pg_search_scope :search_by_car,
    against: [ :brand, :model, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def unreviewed_bookings
    bookings.where.not(id: reviews.pluck(:booking_id).uniq)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  validates :content, length: { minimum: 20 }
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :cars
  has_many :bookings
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]
  def index
    @bookings = policy_scope(Booking).order("created_at DESC")
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      @unreviewed_bookings = @car.unreviewed_bookings
      render "cars/show"
    end
  end

  def show
    @review = Review.new
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :destroy]
  skip_before_action :authenticate_user!,only: [:show, :index ]

  def index
    skip_policy_scope
    if params[:start].present? && params[:end].present?
      # cars = Car.search_by_car(params[:query])
      # # @cars.order("created_at DESC")

      # car_arr = []
      # cars.each do |car|
      #   car.bookings.each do |booking|
      #     if booking.start_date > params[:end] || booking.end_date < params[:start]
      #       car_arr << car
      #     end
      #   end
      # end
      # @cars = car_arr.uniq
      @cars = Car.joins(:bookings).group("cars.id").where("cars.location ILIKE :query AND (bookings.start_date > :end OR bookings.end_date < :start)",
                                                          query: params[:query], end: params[:end], start: params[:start])
    elsif params[:query].present?
      @cars = Car.search_by_car(params[:query])
    else
      @cars = Car.all
    end
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    authorize @car

    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
      respond_to do |format|
        format.json { render :show, status: :created, location: @car }
        format.html
      end
    else
      render :new
      format.json { render json: @car.errors, status: :unprocessable_entity }

    end
  end

  def show
    @booking = Booking.new

    @markers = [
      {
        lat: @car.latitude,
        lng: @car.longitude,
        infoWindow: { content: render_to_string(partial: "/cars/map_box", locals: { car: @car }) }
    }]

    @unreviewed_bookings = @car.unreviewed_bookings
    # @car.bookings
    # @booking = Booking.find_by(user: current_user)
    @review = Review.new

    #calculate average rating
    sum = 0
    count = 0
    @car.reviews.each do |review|
      count += 1
      sum += review.rating
    end
    if sum == 0
      @average_rating = 0
    else
      @average_rating = sum / count
    end
  end

  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:brand, :model, :mileage, :year, :body_type, :location, :price, :transmission, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  layout "home"

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :destroy]
  before_action :set_booking, only: [:index, :create]
  def index
    @reviews = policy_scope(Review).order("created_at DESC")
  end

  def create
    @review = @booking.build_review(review_params)
    # @review = Review.new(review_params)
    # @review.booking = @booking
    @review.user = current_user
    authorize @review
    if @review.save
      @unreviewed_bookings = @booking.car.unreviewed_bookings
      respond_to do |format|
        format.html { redirect_to car_path(@booking.car) }
        format.js
      end
      # redirect_to car_path(@booking.car)
    else
      @unreviewed_bookings = @booking.car.unreviewed_bookings
      respond_to do |format|
        format.html { render 'cars/show' }
        format.js
      end
      # render "cars/show"
    end
  end

  def show
  end

  def destroy
    @review.destroy
    redirect_to reviews_path

  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_review
    @review = Review.find(params[:id])
    authorize @review
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= simple_form_for [@car, booking] do |f| %>
  <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <div class="btn-show text-left"> <%= f.submit %></div>
<% end %>

app/views/bookings/_review_card_booking.html.erb
<% unless booking.review && booking.review.persisted? %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="review-card">
        <% if Date.today >= booking.end_date %>
          <h1>Write a review</h1>
            <!-- <#%= render 'reviews/form', review: review, unreviewed_booking: unreviewed_booking %> -->
          <%= render 'reviews/form', review: review, unreviewed_booking: booking, current_controller_name: "bookings" %>
        <% else %>
          <h2>You can write a review after the booking period</h2>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/index.html.erb
<div class="booking">
  <h1>Your Bookings</h1>
  <div class="bookings-card">
    <div class="container">
      <div class="row">
        <% count = 1 %>
        <% @bookings.each do |booking| %>
          <h5>Your <%= count %>. booking:</h5>
          <% count += 1 %>
          <% unless booking.user != current_user %>
            <%= link_to booking_path(booking) do %>
              <%= link_to booking_path(booking) do %>
                <div class="col-xs-12 col-sm-12 offset-4" >
                  <div class="card-wrapper">
                    <div class="car-card"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path booking.car.photo unless booking.car.photo.blank? %>');">
                      <div class="card-description">
                        <h2><%= booking.car.brand %> <%= booking.car.model %></h2>
                        <h3>$<%= booking.car.price %> per day</h3>
                      </div>
                      <div class="card-price">
                        <h2>From <%= booking.start_date.strftime("%b %d, %Y") %></h2>
                        <h2>to <%= booking.end_date.strftime("%b %d, %Y") %></h2>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="booking">
  <h1>Thank you!</h1>
  <h1>Your booking dates are shown below</h1>
  <h2> <i>Start date: </i><%= @booking.start_date.strftime("%b %d, %Y") %></h2>
  <h2> <i> End date: </i><%= @booking.end_date.strftime("%b %d, %Y") %></h2>
</div>
<div id="review-card-booking">
  <%= render 'bookings/review_card_booking', review: @review, booking: @booking %>
</div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 buttons-options">
      <%= link_to "See your bookings", bookings_path, class: 'btn btn-primary' %>
      <%= link_to "Back to listings", cars_path, class: 'btn btn-primary' %>
      <%= link_to "Cancel Booking", booking_path,
            method: :delete,
            data: { confirm: "Are you sure you want to cancel your booking?" }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<%= simple_form_for(car) do |f| %>
  <div class = "textforform">
    <div class= "form-input"> <%= f.input :brand, label: "Brand", placeholder: "e.g. Ferrari" %></div>
    <div class= "form-input"> <%= f.input :model, label: "Model", placeholder: "e.g. Enzo" %></div>
    <div class= "form-input"> <%= f.input :mileage, label: "Mileage", hint: "Please list the mileage in miles" %></div>
    <div class= "form-input"> <%= f.input :year, label: "Year", collection: 1950..2018 %></div>
    <div class= "form-input"> <%= f.input :body_type, label: "Body Type", placeholder: "e.g. Coupe", collection: %w(Convertible Coupe Sedan SUV Wagon) %></div>
    <div class= "form-input"> <%= f.input :location, label: "Location", placeholder: "Enter your address" %></div>
    <div class= "form-input"> <%= f.input :transmission, label: "Transmission",collection: %w(Automatic Manual) %></div>
    <div class= "form-input">  <%= f.input :price, label: "Price per day (USD)" %> </div>
    <div class= "form-input"> <%= f.input :photo %> </div>
    <div class= "form-input"> <%= f.input :photo_cache, as: :hidden %> </div>
    <div class="nice-button"><%= f.submit class: "btn btn-primary" %></div>
  </div>
<% end %>

app/views/cars/_map_box.html.erb
<h4><%= car.brand %> </h4>
<h4><%= car.location %> </h4>

app/views/cars/_review_card.html.erb
<% unreviewed_bookings.each do |unreviewed_booking| %>
  <div class="col-xs-12 offset-sm-6">
    <div class="review-separator">
      <p>Booking made on <strong> <%= unreviewed_booking.created_at.strftime("%b %e, %Y - %l:%M %p") %></strong></p>
      <p>Booked from: <strong><%= unreviewed_booking.start_date.strftime("%b %d, %Y") %></strong> to: <strong><%= unreviewed_booking.end_date.strftime("%b %d, %Y") %></strong></p>
      <% if Date.today >= unreviewed_booking.end_date %>
        <% if review.booking == unreviewed_booking %>
          <%= render 'reviews/form', review: review, unreviewed_booking: unreviewed_booking, current_controller_name: "cars" %>
        <% else %>
          <%= render 'reviews/form', review: Review.new, unreviewed_booking: unreviewed_booking, current_controller_name: "cars" %>
        <% end %>
      <% else %>
        <h5> <i> - You can write a review after the booking period -</i></h5>
      <% end %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class= "header title-padding">
  <h1><strong>Pick your dream ride</strong></h1>
</div>
<div class="header">
  <%= form_tag cars_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query], placeholder: "Search brand, model", class: "form-tag-index"%>
    <%= submit_tag "Search" , class: "btn btn-primary"%>
  <% end %>
</div>
<div class="wrapper-index">
  <div class="container">
    <div class="row">
      <% @cars.each do |car| %>
        <div class="col-sm-12 col-md-6">
          <div class="card-wrapper">
            <%= link_to car_path(car) do %>
              <div class="car-card"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path car.photo unless car.photo.blank? %>');">
                <div class="card-description">
                  <h2><%= car.brand %> <%= car.model %></h2>
                </div>
                <div class="card-price">
                  <h3>$<%= car.price %> per day</h3>
                </div>
                <div class="card-location">
                  <h3><%= car.location %> </h3>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class= "imagen" style=" background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://ncucsprojects.com/cptr304/26120459/XPSCarRentals/images/banner.jpg'); background-size: cover;">
  <p>
    <h1 class="title-listing">List your Car</h1>
  </p>
</div>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <%= render 'form', car: @car %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="text-center title-padding">
  <h1><%= @car.brand %> <%= @car.model %></h1>
  <div class="show_image">
    <%= cl_image_tag @car.photo, height: 500, width: 800, crop: :fill%>
    <h2>Average Rating</h2>
    <% if @average_rating %>
      <% @average_rating.times do %>
        <i class="fas fa-star yellow-star"></i>
      <% end %>
    <% end %>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-2">
      <div class= "new-desc-card">
        <h4><%= @car.brand %> <%= @car.model %></h4>
        <table>
          <tr>
            <td>Year:</td>
            <td><%= @car.year %></td>
          </tr>
          <tr>
            <td>Mileage:</td>
            <td><%= @car.mileage %> miles</td>
          </tr>
          <tr>
            <td>Body Type:</td>
            <td><%= @car.body_type %></td>
          </tr>
          <tr>
            <td>Transmission:</td>
            <td><%= @car.transmission %></td>
          </tr>
          <tr>
            <td>Location:</td>
            <td><%= @car.location %></td>
          </tr>
          <tr>
            <td>Price:</td>
            <td><%= @car.price %> USD</td>
          </tr>
        </table>
        <div class="wrapper-button">
          <div class="item">
            <% unless @car.user != current_user %>
              <%= link_to "Delete listing", car_path(@car),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this listing?" },class: 'btn btn-danger'
            %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% unless @car.user == current_user %>
      <div class="wrapper-booking-form">
        <div class="col-sm-4 col-sm-offset-0">
          <div class="booking-card">
            <h3>Book your car</h3>
            <%= render 'bookings/form', booking: @booking %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-sm-offset-2">
      <div class="map-style">
        <div class= "location-car">
          <p> Location to your dream car: </p>
          <p><i><%= @car.location  %></i></p>
        </div>
        <div
        id="map"
        style="width: 800px;
        height: 600px;"
        data-markers="<%= @markers.to_json %>">
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% if @unreviewed_bookings.any? %>
      <div class="row">
        <h1 class="text-center">Write A Review</h1>
        <div class="review-card" id="review-card">
          <%= render 'cars/review_card', review: @review, unreviewed_bookings: @unreviewed_bookings %>
        </div>
      </div>
    <% end %>
    <hr>
    <h1 class="text-center">Reviews</h1>
    <hr>
    <div class="row" id="reviews">
      <% @car.reviews.order("created_at DESC").each do |review| %>
        <%= render 'reviews/show', review: review %>
      <% end %>
    </div>
  </div>
  <div class = "btns-center">
    <%= link_to "Go to listings", cars_path, class: 'btn btn-primary'%>
  </div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0) 0%, rgba(0,36,61,0.40) 50%), url('https://res.cloudinary.com/jphoga/image/upload/v1534234625/landing.jpg');">
  <div class="banner-content">
    <label class="sr-only" for="inlineFormInputName2"></label>
    <h1>Rent the car of your dreams</h1>
    <div class="black-font">
      <%= form_tag cars_path, method: :get  do %>
        <%= text_field_tag :query,
            params[:query], placeholder: "Search location", class: "form-tag"%>
        <%= date_field_tag :start,
            params[:start], class: "form-tag"%>
        <%= date_field_tag :end,
            params[:end], class: "form-tag"%>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
      <p>
        <span id="banner-typed-text"></span>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_navbar-landing.html.erb
<div class="navbar-wagon-landing navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag ("") %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "List your car", new_car_path %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fas fa-book"></i>  <%= "My Bookings" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <!-- <%#= link_to t("List Your Car"), new_car_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to bookings_path do %>
            <i class="fas fa-book"></i>  <%= "My Bookings" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon .navbar.navbar-default navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag ("sportscar.png") %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <h4><%= link_to "List your car", new_car_path %></h4>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fas fa-book"></i>  <%= "My Bookings" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <!-- <%#= link_to t("List Your Car"), new_car_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to bookings_path do %>
            <i class="fas fa-book"></i>  <%= "My Bookings" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Supercar Rental</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="padding-top : 60px ;" >
    <%= render 'layouts/navbar' %>
    <%= render 'flashes' %>
    <%= yield %>
     <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV["GOOGLE_API_BROWSER_KEY"]}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Supercar Rental</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'layouts/navbar-landing' %>
    <%= render 'flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'layouts/banner' %>

app/views/reviews/_form.html.erb
<%= simple_form_for [unreviewed_booking, review], remote: true do |f| %>
  <div class = "textforform">
    <div class= "form-input rating"> <%= f.input :rating, as: :radio_buttons, collection: [1,2,3,4,5] %></div>
    <div class= "form-input"> <%= f.input :content %></div>
    <div class= "form-input"> <%= f.hidden_field :origin_controller, value: current_controller_name %></div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reviews/_show.html.erb
<div class="review-separator">
  <h5><%= cl_image_tag review.user.photo, class: "avatar img-circle" %><strong> By <%= review.user.first_name %> <%= review.user.last_name %> from <i><%= review.created_at.strftime("%b %Y") %></i></strong>
  </h5>
  <% review.rating.times do %>
    <i class="fas fa-star yellow-star"></i>
  <% end %>
  <p><%= review.content %></p>
</div>

app/views/reviews/create.js.erb
console.log("<%= params[:review][:origin_controller] %>")

<% if params[:review][:origin_controller] == "cars" %>

  function refreshForm(innerHTML) {
    const newReviewForm = document.getElementById('review-card');
    newReviewForm.innerHTML = innerHTML;
  }

  function addReview(reviewHTML) {
    const reviews = document.getElementById('reviews');
    reviews.insertAdjacentHTML('afterbegin', reviewHTML);
  }

  <% if @review.errors.any? %>

    refreshForm('<%= j render "cars/review_card", review: @review, unreviewed_bookings: @unreviewed_bookings, current_controller_name: "cars" %>');
  <% else %>
    addReview('<%= j render "reviews/show", review: @review %>');

    refreshForm('<%= j render "cars/review_card", review: Review.new, unreviewed_bookings: @unreviewed_bookings, current_controller_name: "cars" %>');
  <% end %>

<% elsif params[:review][:origin_controller] == "bookings" %>

  function refreshForm(innerHTML) {
    const newReviewForm = document.getElementById('review-card-booking');
    newReviewForm.innerHTML = innerHTML;
  }


  refreshForm('<%= j render "bookings/review_card_booking", review: @review, booking: @booking, current_controller_name: "bookings" %>');


<% end %>